Us 16
beedawn/scrapescholar pull request #136
Opened 2024-10-18 00:40 UTC by beedawn

Tests completed.

2024-10-18 21:16 UTC, brilzen requested changes
may be add .DS_Store to git ignore files

2024-10-18 21:16 UTC, brilzen commented on backend/.DS_Store
do we need to check in these .DS_Store files

2024-10-18 21:16 UTC, brilzen commented on backend/auth_tools/.DS_Store
do we need to check in these .DS_Store files

2024-10-18 21:23 UTC, beedawn commented on backend/auth_tools/.DS_Store
Good call, I removed them.

2024-10-18 21:24 UTC, brilzen approved these changes

2024-10-20 23:11 UTC, tristanhamid approved these changes
Sorry for the delay!

2024-10-20 23:35 UTC, merged